language: python
python:
  - '3.6'
before_install:
  # Decrypt and un-tar private files.
  # https://docs.travis-ci.com/user/encrypting-files/#encrypting-multiple-files
  - openssl aes-256-cbc -K $encrypted_707010ae36e6_key -iv $encrypted_707010ae36e6_iv -in private/private.tar.enc -out private/private.tar -d
  - tar xvf private/private.tar --directory private
install: pip install -r requirements.build.txt
script: inv build
deploy:
  - provider: script
    skip_cleanup: true
    script: inv deploy
    on:
      branch: master
