language: python
python:
  - '3.6'
before_install:
  - openssl aes-256-cbc -K $encrypted_197ba148e8cc_key -iv $encrypted_197ba148e8cc_iv -in private/private.tar.enc -out private/private.tar -d
  - tar xvf private/private.tar --directory private
install: pip install -r requirements.build.txt
script: inv build
deploy:
  - provider: script
    skip_cleanup: true
    script: inv deploy
    on:
      branch: master
