[project]
name = "esmithy-blog"
version = "0.1.0"
description = "Pelican blog for esmithy.net"
requires-python = ">=3.14"
dependencies = [
    "invoke",
    "markdown",
    "pelican",
    "pelican-readtime",
    "pelican-search",
    "pelican-sitemap",
]

[dependency-groups]
dev = [
    "pre-commit",
    "ruff",
]

[tool.ruff]
target-version = "py314"
